--HQL REFACTORING 360_MOVIMIENTOS_PARQUE
SET hive.cli.print.header = FALSE;

SET hive.vectorized.execution.enabled = FALSE;

SET hive.vectorized.execution.reduce.enabled = FALSE;
--SE CAMBIO EN RF
SET tez.queue.name = ${VAL_COLA_EJECUCION};
--ELIMINA LA DATA PRE EXISTENTE
DELETE
FROM
	${ESQUEMA_TABLA}.otc_t_alta_baja_hist
WHERE
	TIPO = 'ALTA'
	AND FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}';
--INSERTA LA DATA DEL MES
INSERT
	INTO
	${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST
SELECT 
	'ALTA' AS TIPO
	, TELEFONO
	, FECHA_ALTA AS FECHA
	, CANAL_COMERCIAL AS CANAL
	, SUB_CANAL
	, CAST( NULL AS STRING) AS NUEVO_SUB_CANAL
	, PORTABILIDAD
	, Operadora_origen
	, 'MOVISTAR (OTECEL)' AS Operadora_destino
	, CAST( NULL AS STRING) AS motivo
	, NOM_DISTRIBUIDOR AS DISTRIBUIDOR
	, OFICINA
	--INSERTADO EN RF----------------------------
	, CASE
		WHEN LINEA_NEGOCIO LIKE '%H%BRIDO'
		AND upper(PORTABILIDAD)= 'NO' THEN 'ALTA POSPAGO'
		WHEN LINEA_NEGOCIO LIKE '%POSPAGO%'
		AND upper(PORTABILIDAD)= 'NO' THEN 'ALTA POSPAGO'
		WHEN LINEA_NEGOCIO LIKE '%POSPAGO%'
		AND upper(PORTABILIDAD)= 'SI' THEN 'ALTA PORTABILIDAD POSPAGO'
		WHEN LINEA_NEGOCIO LIKE '%POSPAGO%'
		AND upper(PORTABILIDAD)= 'INTRA' THEN 'ALTA PORTABILIDAD POSPAGO'
		WHEN LINEA_NEGOCIO LIKE '%PREPAGO%'
		AND upper(PORTABILIDAD)= 'NO' THEN 'ALTA PREPAGO'
		WHEN LINEA_NEGOCIO LIKE '%PREPAGO%'
		AND upper(PORTABILIDAD)= 'SI' THEN 'ALTA PORTABILIDAD PREPAGO'
		WHEN LINEA_NEGOCIO LIKE '%PREPAGO%'
		AND upper(PORTABILIDAD)= 'INTRA' THEN 'ALTA PORTABILIDAD PREPAGO'
		ELSE ''
	END AS SUB_MOVIMIENTO
	, imei
	, equipo
	, icc
	, ciudad
	, provincia
	, cod_categoria
	, domain_login_ow
	, nombre_usuario_ow
	, domain_login_sub
	, nombre_usuario_sub
	, forma_pago
	, cod_da
	, nom_usuario
	, campania
	, codigo_distribuidor
	, codigo_plaza
	, nom_plaza
	, region
	, provincia_ivr
	, ejecutivo_asignado_ptr
	, area_ptr
	, codigo_vendedor_da_ptr
	, jefatura_ptr
	, provincia_ms
	, codigo_usuario
	, calf_riesgo
	, cap_endeu
	, valor_cred
	, CAST(NULL AS string) AS vol_invol
	, account_num
	, distribuidor AS distribuidor_crm
	, canal AS canal_transacc
	, (nvl(tarifa_plan_actual_ov, tarifa_basica))-(nvl(descuento_tarifa_plan_act, 0)) AS TARIFA_FINAL_PLAN_ACT  --**OJO
	, descuento_tarifa_plan_act
	, tarifa_plan_actual_ov
	, descripcion_descuento_plan_act --**OJO
	----xxxxxxxxxxxxxxxxxxxxxxxx---------  
FROM
	${ESQUEMA_CS_ALTAS}.otc_t_altas_bi
WHERE
	p_fecha_proceso = '${fecha_movimientos_cp}'
	AND marca = 'TELEFONICA'
;
--ELIMINA LA DATA PRE EXISTENTE
DELETE
FROM
	${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST
WHERE
	TIPO = 'BAJA'
	AND FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}';
--INSERTA LA DATA DEL MES
INSERT
	INTO
	${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST
SELECT
	'BAJA' AS TIPO
	, TELEFONO
	, FECHA_BAJA AS FECHA
	, CAST(NULL AS STRING) AS CANAL
	, CAST(NULL AS STRING) AS SUB_CANAL
	, CAST(NULL AS STRING) AS NUEVO_SUB_CANAL
	, PORTABILIDAD
	, 'MOVISTAR (OTECEL)' AS Operadora_origen
	, Operadora_destino
	, MOTIVO_BAJA AS motivo
	, CAST(NULL AS STRING) AS DISTRIBUIDOR
	, CAST(NULL AS STRING) AS OFICINA
	--INSERTADO EN RF
	, 'BAJA CHARGEBACK' AS SUB_MOVIMIENTO
	, CAST(NULL AS STRING) AS IMEI
	, CAST(NULL AS STRING) AS EQUIPO
	, CAST(NULL AS STRING) AS ICC
	, CAST(NULL AS STRING) AS CIUDAD
	, CAST(NULL AS STRING) AS PROVINCIA
	, CAST(NULL AS STRING) AS COD_CATEGORIA
	, CODIGO_USUARIO AS DOMAIN_LOGIN_OW
	, CAST(NULL AS STRING) AS NOMBRE_USUARIO_OW
	, CAST(NULL AS STRING) AS DOMAIN_LOGIN_SUB
	, CAST(NULL AS STRING) AS NOMBRE_USUARIO_SUB
	, CAST(NULL AS STRING) AS FORMA_PAGO
	, CAST(NULL AS STRING) AS COD_DA
	, CAST(NULL AS STRING) AS NOM_USUARIO
	, CAST(NULL AS STRING) AS CAMPANIA
	, CAST(NULL AS STRING) AS CODIGO_DISTRIBUIDOR
	, CAST(NULL AS STRING) AS CODIGO_PLAZA
	, CAST(NULL AS STRING) AS NOM_PLAZA
	, CAST(NULL AS STRING) AS REGION
	, CAST(NULL AS STRING) AS PROVINCIA_IVR
	, EJECUTIVO_ASIGNADO_PTR
	, AREA_PTR
	, CODIGO_VENDEDOR_DA_PTR
	, JEFATURA_PTR
	, CAST(NULL AS STRING) AS PROVINCIA_MS
	, CAST(NULL AS STRING) AS CODIGO_USUARIO
	, CAST(NULL AS STRING) AS CALF_RIESGO
	, CAST(NULL AS STRING) AS CAP_ENDEU
	, CAST(NULL AS INT) AS VALOR_CRED
	, (CASE
		WHEN MOTIVO_BAJA = 'COBRANZAS' THEN 'INVOLUNTARIO'
		ELSE 'VOLUNTARIO'
	END) AS VOL_INVOL
	, account_no AS account_num
	, CAST(NULL AS STRING) AS distribuidor_crm
	, CAST(NULL AS STRING) AS canal_transacc
	, CAST(NULL AS DOUBLE) AS TARIFA_FINAL_PLAN_ACT
	, CAST(NULL AS DOUBLE) AS descuento_tarifa_plan_act
	, CAST(NULL AS DOUBLE) AS tarifa_plan_actual_ov
	, CAST(NULL AS STRING) AS descripcion_descuento_plan_act
	---------------------------------------XXXXXXXXXXXXXXXXXXXXXXXXXXXX-----------------------------
FROM
	${ESQUEMA_CS_ALTAS}.otc_t_BAJAS_bi
WHERE
	p_FECHA_PROCESO = '${fecha_movimientos_cp}'
	AND marca = 'TELEFONICA';
--ELIMINA LA DATA PRE EXISTENTE DEL MES QUE SE PROCESA
DELETE
FROM
	${ESQUEMA_TABLA}.otc_t_transfer_hist
WHERE
	TIPO = 'PRE_POS'
	AND FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}';
--INSERTA LA DATA DEL MES
INSERT
	INTO
	${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST
SELECT
	'PRE_POS' AS TIPO
	, TELEFONO
	, FECHA_TRANSFERENCIA AS FECHA
	, CANAL_USUARIO AS CANAL
	, SUB_CANAL
	, CAST(NULL AS STRING) AS NUEVO_SUB_CANAL
	, NOM_DISTRIBUIDOR_USUARIO AS DISTRIBUIDOR
	, OFICINA_USUARIO AS OFICINA
	--INSERTADO EN RF
	, 'TRANSFER IN POSPAGO' AS SUB_MOVIMIENTO
	, IMEI
	, EQUIPO
	, ICC
	, DOMAIN_LOGIN_OW
	, NOMBRE_USUARIO_OW
	, DOMAIN_LOGIN_SUB
	, NOMBRE_USUARIO_SUB
	, FORMA_PAGO
	, CANAL AS canal_transacc
	, CAMPANIA
	, CODIGO_DISTRIBUIDOR_USUARIO AS CODIGO_DISTRIBUIDOR
	, CODIGO_PLAZA_USUARIO AS CODIGO_PLAZA
	, NOM_PLAZA_USUARIO AS NOM_PLAZA
	, REGION_USUARIO AS REGION
	, CAST( NULL AS STRING) AS RUC_DISTRIBUIDOR -- ELIMINAR 
	, EJECUTIVO_ASIGNADO_PTR
	, AREA_PTR
	, CODIGO_VENDEDOR_DA_PTR
	, JEFATURA_PTR
	, CODIGO_USUARIO
	, CALF_RIESGO
	, CAP_ENDEU
	, VALOR_CRED
	, ACCOUNT_NUM_ANTERIOR
	, CIUDAD_USUARIO
	, PROVINCIA_USUARIO
	, ciudad
	, codigo_plan_anterior AS COD_PLAN_ANTERIOR
	, nombre_plan_anterior AS DES_PLAN_ANTERIOR
	, distribuidor AS distribuidor_crm
	, (nvl(tarifa_ov_plan_act, tarifa_basica))-(nvl(descuento_tarifa_plan_act, 0)) AS TARIFA_FINAL_PLAN_ACT --** OJO
	, descuento_tarifa_plan_act
	, tarifa_ov_plan_act
	-------------------------XXXXXXXXXXXXXXXXXXXX---------------------------------
FROM
	${ESQUEMA_CS_ALTAS}.otc_t_transfer_in_bi
WHERE
	P_FECHA_PROCESO = '${fecha_movimientos_cp}'
;
--ELIMINA LA DATA PRE EXISTENTE
DELETE
FROM
	${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST
WHERE
	TIPO = 'POS_PRE'
	AND FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}';
--INSERTA LA DATA DEL MES
INSERT
	INTO
	${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST
SELECT
	'POS_PRE' AS TIPO
	, TELEFONO
	, FECHA_TRANSFERENCIA AS FECHA
	, CANAL_USUARIO AS CANAL
	, SUB_CANAL
	, CAST(NULL AS STRING) AS NUEVO_SUB_CANAL
	, NOM_DISTRIBUIDOR_USUARIO AS DISTRIBUIDOR
	, OFICINA_USUARIO AS OFICINA
	-----------------	INSERTADO EN RF
	, 'TRANSFER OUT PREPAGO' AS SUB_MOVIMIENTO
	, IMEI
	, EQUIPO
	, ICC
	, DOMAIN_LOGIN_OW
	, NOMBRE_USUARIO_OW
	, DOMAIN_LOGIN_SUB
	, NOMBRE_USUARIO_SUB
	, FORMA_PAGO
	, CANAL AS canal_transacc
	, CAMPANIA_USUARIO AS CAMPANIA
	, CODIGO_DISTRIBUIDOR_USUARIO AS CODIGO_DISTRIBUIDOR
	, CODIGO_PLAZA_USUARIO AS CODIGO_PLAZA
	, NOM_PLAZA_USUARIO AS NOM_PLAZA
	, REGION_USUARIO AS REGION
	, CAST( NULL AS STRING) AS RUC_DISTRIBUIDOR -- ELIMINAR 
	, EJECUTIVO_ASIGNADO_PTR
	, AREA_PTR
	, CODIGO_VENDEDOR_DA_PTR
	, JEFATURA_PTR
	, CODIGO_USUARIO
	, CAST(NULL AS STRING) AS CALF_RIESGO
	, CAST(NULL AS STRING) AS CAP_ENDEU
	, CAST(NULL AS INT) AS VALOR_CRED
	, ACCOUNT_NUM_ANTERIOR
	, CIUDAD_USUARIO
	, PROVINCIA_USUARIO
	, ciudad
	, codigo_plan_anterior AS COD_PLAN_ANTERIOR
	, nombre_plan_anterior AS DES_PLAN_ANTERIOR
	, distribuidor AS distribuidor_crm
	, CAST(NULL AS DOUBLE) AS TARIFA_FINAL_PLAN_ACT
	, CAST(NULL AS DOUBLE) AS descuento_tarifa_plan_act
	, CAST(NULL AS DOUBLE) AS tarifa_ov_plan_act
	--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
FROM
	${ESQUEMA_CS_ALTAS}.otc_t_transfer_out_bi
WHERE
	p_fecha_proceso = '${fecha_movimientos_cp}'
;
--ELIMINA LA DATA PRE EXISTENTE	
DELETE
FROM
	${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST
WHERE
	FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}';
--INSERTA LA DATA DEL MES
INSERT
	INTO
	${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST
SELECT
	TIPO_MOVIMIENTO AS TIPO
	, TELEFONO
	, FECHA_CAMBIO_PLAN AS FECHA
	, CANAL
	, SUB_CANAL
	, CAST(NULL AS varchar(50)) AS NUEVO_SUB_CANAL
	, NOM_DISTRIBUIDOR AS DISTRIBUIDOR
	, OFICINA
	, CODIGO_PLAN_ANTERIOR AS COD_PLAN_ANTERIOR
	, DESCRIPCION_PLAN_ANTERIOR AS DES_PLAN_ANTERIOR
	, TARIFA_OV_PLAN_ANT AS TB_DESCUENTO
	, DESCUENTO_TARIFA_PLAN_ANT AS TB_OVERRIDE
	, DELTA
	--INSERTADO EN RF 
	, (CASE
		WHEN (DELTA >= -0.99
			AND DELTA < 0) THEN 'CAMBIO DE PLAN POSICIONAMIENTO'
		WHEN (DELTA > 0
			AND DELTA <= 0.99) THEN 'CAMBIO DE PLAN POSICIONAMIENTO'
		WHEN DELTA = 0 THEN 'CAMBIO DE PLAN MISMA TARIFA'
		WHEN DELTA >= 1.0 THEN 'CAMBIO DE PLAN UPSELL'
		WHEN DELTA <= 1.0 THEN 'CAMBIO DE PLAN DOWNSELL CHARGEBACK'
		ELSE ''
	END)
    AS SUB_MOVIMIENTO
	, CODIGO_USUARIO_ORDEN AS DOMAIN_LOGIN_OW
	, NOMBRE_USUARIO_ORDEN AS NOMBRE_USUARIO_OW
	, CODIGO_USUARIO_SUBMIT AS DOMAIN_LOGIN_SUB
	, NOMBRE_USUARIO_SUBMIT AS NOMBRE_USUARIO_SUB
	, FORMA_PAGO
	, CAMPANIA
	, CAST(NULL AS varchar(60)) AS CODIGO_DISTRIBUIDOR
	, CAST(NULL AS varchar(60)) AS CODIGO_PLAZA
	, CAST(NULL AS varchar(110)) AS NOM_PLAZA
	, CAST(NULL AS STRING) AS REGION
	, CAST(NULL AS STRING) AS RUC_DISTRIBUIDOR -- ELIMINAR 
	, TARIFA_BASICA_ANTERIOR
	, FECHA_INICIO_PLAN_ANTERIOR
	, TARIFA_FINAL_PLAN_ACT
	, TARIFA_FINAL_PLAN_ANT
	, PROVINCIA
	, descripcion_descuento_plan_act
	, descuento_tarifa_plan_act
	, tarifa_plan_actual_ov
	-------------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-------------------------------------
FROM
	${ESQUEMA_CS_ALTAS}.otc_t_cambio_plan_bi
WHERE
	p_fecha_proceso = ${fecha_movimientos_cp};
-----------------------------INSERTADO EN RF-PARA INCLUIR TABLA NO RECLICLABLES--------------------------
--ELIMINA LA DATA PRE EXISTENTE
DELETE
FROM
	${ESQUEMA_TABLA}.OTC_T_NO_RECICLABLE_HIST
WHERE
	TIPO = 'NO_RECICLABLE'
	AND FECHA_PROCESO = '${fecha_movimientos}';
--INSERTA LA DATA DEL MES
INSERT
	INTO
	${ESQUEMA_TABLA}.otc_t_no_reciclable_hist
SELECT
	'NO_RECICLABLE' AS TIPO
	, 'NO RECICLABLE' AS SUB_MOVIMIENTO
	, NUM_TELEFONICO AS TELEFONO
	, FECHA_ALTA AS FECHA
	, DOCUMENTO_CLIENTE_ACT
	, FECHA_PROCESO
	, CAST(NULL AS STRING) AS CANAL_COMERCIAL
	, CAST(NULL AS STRING) AS CAMPANIA
	, CAST(NULL AS STRING) AS CODIGO_DISTRIBUIDOR
	, CAST(NULL AS varchar(110)) AS NOM_DISTRIBUIDOR
	, CAST(NULL AS varchar(60)) AS CODIGO_PLAZA
	, CAST(NULL AS varchar(110)) AS NOM_PLAZA
	, CAST(NULL AS STRING) AS REGION
	, CAST( NULL AS STRING) AS RUC_DISTRIBUIDOR -- ELIMINAR 
	, LINEA_NEGOCIO_BAJA
	, DOCUMENTO_CLIENTE_ANT
	, DIAS
	, FECHA_BAJA
	------------MODIFICADO FORMATO FECHA YYYY-MM-DD
FROM
	${ESQUEMA_CS_ALTAS}.no_reciclable
WHERE
	FECHA_PROCESO = '${fecha_movimientos}'
	AND marca = 'TELEFONICA';
-----------------------********************************-------------------------------
------------------------PROCESO ALTAS BAJAS REPROCESO---------------------------------
-----------------------********************************-------------------------------
---TABLA QUE ALMACENA LAS ALTAS DE TODOS LOS DIAS (particiones)
--PARA UN DETERMINADO MES DE ANALISIS: tmp_altas_ttls_mes 
DROP TABLE IF EXISTS ${ESQUEMA_TEMP}.tmp_altas_ttls_mes;

CREATE TABLE ${ESQUEMA_TEMP}.tmp_altas_ttls_mes AS 
SELECT
	DISTINCT
telefono
	, linea_negocio
	, account_num
	, fecha_alta
	, cliente
	, documento_cliente
	, nombre_plan
	, icc
	, fecha_proceso AS fecha_baja
	, domain_login_ow
	, nombre_usuario_ow
	, domain_login_sub
	, nombre_usuario_sub
	, canal AS canal_transacc
	, distribuidor AS distribuidor_crm
	, oficina
	, portabilidad
	, forma_pago
	, cod_da
	, nom_usuario
	, canal_comercial AS canal
	, campania
	, codigo_distribuidor
	, nom_distribuidor AS distribuidor
	, codigo_plaza
	, nom_plaza
	, region
	, sub_canal
	, operadora_origen
	, imei
	, equipo
	, ejecutivo_asignado_ptr
	, area_ptr
	, codigo_vendedor_da_ptr
	, jefatura_ptr
	, codigo_usuario
	, calf_riesgo
	, cap_endeu
	, valor_cred
FROM
	${ESQUEMA_CS_ALTAS}.otc_t_altas_bi
	-- el between debe ser siempre desde 02 del mes analisis hasta fecha eje dia 
	-- p_fecha_proceso no puede tomar el valor del dia 1, ya que es cierre de mes 
WHERE
	p_fecha_proceso BETWEEN '${f_inicio_abr}' AND '${f_fin_abr}'
	AND marca = 'TELEFONICA';
--- TABLA QUE ALMACENA LOS TELEFONOS DE LOS MOVIMIENTOS:
---ALTAS, TRANSFER IN, TRANSFER OUT, CAMBIOS DE PLAN, A MES CAIDO,(O FECHA EJE +1)
---SE TENDRA UNA INFORMACION REAL A MES CAIDO ej: yyyymm01
---DENOMINADOS MOVIMIENTOS EFECTIVOS: tmp_movimientos_efctvs
DROP TABLE ${ESQUEMA_TEMP}.tmp_movimientos_efctvs;

CREATE TABLE ${ESQUEMA_TEMP}.tmp_movimientos_efctvs AS 
SELECT
	DISTINCT
telefono
FROM
	${ESQUEMA_CS_ALTAS}.otc_t_altas_bi
WHERE
	p_FECHA_PROCESO = '${fecha_movimientos_cp}'
	AND marca = 'TELEFONICA'
UNION ALL
SELECT
	DISTINCT
telefono
FROM
	${ESQUEMA_CS_ALTAS}.otc_t_transfer_in_bi
WHERE
	p_FECHA_PROCESO = '${fecha_movimientos_cp}'
	AND marca = 'TELEFONICA'
UNION ALL
SELECT
	DISTINCT
telefono
FROM
	${ESQUEMA_CS_ALTAS}.otc_t_transfer_OUT_bi
WHERE
	p_FECHA_PROCESO = '${fecha_movimientos_cp}'
	AND marca = 'TELEFONICA'
UNION ALL
SELECT
	DISTINCT
telefono
FROM
	${ESQUEMA_CS_ALTAS}.otc_t_cambio_plan_bi
WHERE
	p_FECHA_PROCESO = '${fecha_movimientos_cp}'
	AND marca = 'TELEFONICA';
--TABLA DE ALTAS BAJAS REPROCESO 
DELETE
FROM
	${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_REPROCESO_HIST
WHERE
	tipo = 'ALTA_BAJA'
	--AND FECHA_proceso BETWEEN '${f_inicio}' AND '${fecha_proceso}';
	AND FECHA_alta BETWEEN '${f_inicio}' AND '${fecha_proceso}';

INSERT
	INTO
	${ESQUEMA_TABLA}.otc_t_alta_baja_reproceso_hist 
SELECT
	telefono
	, cliente
	, fecha_alta
	, fecha_baja
	, portabilidad
	, (CASE 
		WHEN linea_negocio LIKE '%H%BRIDO%' THEN 'POSPAGO'
		WHEN linea_negocio LIKE '%POSPAGO%' THEN 'POSPAGO'
		ELSE linea_negocio
	END) AS linea_negocio
	, 'ALTA_BAJA' AS tipo
	, 'ALTAS BAJAS REPROCESO' AS SUB_MOVIMIENTO
	, account_num
	, documento_cliente
	, nombre_plan
	, icc
	, domain_login_ow
	, nombre_usuario_ow
	, domain_login_sub
	, nombre_usuario_sub
	, canal_transacc
	, distribuidor_crm
	, oficina
	, forma_pago
	, cod_da
	, nom_usuario
	, canal
	, campania
	, codigo_distribuidor
	, distribuidor
	, codigo_plaza
	, nom_plaza
	, region
	, sub_canal
	, operadora_origen
	, imei
	, equipo
	, ejecutivo_asignado_ptr
	, area_ptr
	, codigo_vendedor_da_ptr
	, jefatura_ptr
	, codigo_usuario
	, calf_riesgo
	, cap_endeu
	, valor_cred
FROM
	(
	SELECT
		atm.*
		, ROW_NUMBER() OVER(PARTITION BY atm.telefono
		, atm.fecha_alta
		, atm.linea_negocio
	ORDER BY
		atm.fecha_baja DESC) AS rnum
	FROM
		${ESQUEMA_TEMP}.tmp_altas_ttls_mes atm
	LEFT JOIN (
		SELECT
			telefono
		FROM
			${ESQUEMA_TEMP}.tmp_movimientos_efctvs) me
        ON
		atm.telefono = me.telefono
	WHERE
		me.telefono IS NULL
) tt
WHERE
	rnum = 1;
--OBTIENE EL ULTIMO EVENTO DEL ALTA EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.otc_t_alta_hist_unic;

CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_ALTA_HIST_UNIC AS
SELECT
	XX.TIPO
	, XX.TELEFONO
	, XX.FECHA
	, XX.CANAL
	, XX.SUB_CANAL
	, XX.NUEVO_SUB_CANAL
	, XX.PORTABILIDAD
	, XX.Operadora_origen
	, XX.Operadora_destino
	, XX.motivo
	, XX.DISTRIBUIDOR
	, XX.OFICINA
	--INSERTADO EN RF
	, XX.SUB_MOVIMIENTO
	, XX.IMEI
	, XX.EQUIPO
	, XX.ICC
	, XX.CIUDAD
	, XX.PROVINCIA
	, XX.COD_CATEGORIA
	, XX.DOMAIN_LOGIN_OW
	, XX.NOMBRE_USUARIO_OW
	, XX.DOMAIN_LOGIN_SUB
	, XX.NOMBRE_USUARIO_SUB
	, XX.FORMA_PAGO
	, XX.COD_DA
	, XX.NOM_USUARIO
	, XX.CAMPANIA
	, XX.CODIGO_DISTRIBUIDOR
	, XX.CODIGO_PLAZA
	, XX.NOM_PLAZA
	, XX.REGION
	, XX.PROVINCIA_IVR
	, XX.EJECUTIVO_ASIGNADO_PTR
	, XX.AREA_PTR
	, XX.CODIGO_VENDEDOR_DA_PTR
	, XX.JEFATURA_PTR
	, XX.PROVINCIA_MS
	, XX.CODIGO_USUARIO
	, XX.CALF_RIESGO
	, XX.CAP_ENDEU
	, XX.VALOR_CRED
	, XX.VOL_INVOL
	, XX.ACCOUNT_NUM
	, XX.distribuidor_crm
	, XX.canal_transacc
	, XX.TARIFA_FINAL_PLAN_ACT
	, XX.descuento_tarifa_plan_act
	, XX.tarifa_plan_actual_ov
	, XX.descripcion_descuento_plan_act
FROM
	(
	SELECT
		AA.TIPO
		, AA.TELEFONO
		, AA.FECHA
		, AA.CANAL
		, AA.SUB_CANAL
		, AA.NUEVO_SUB_CANAL
		, AA.PORTABILIDAD
		, AA.Operadora_origen
		, AA.Operadora_destino
		, AA.motivo
		, AA.DISTRIBUIDOR
		, AA.OFICINA
		--INSERTADO EN RF
		, AA.SUB_MOVIMIENTO
		, AA.IMEI
		, AA.EQUIPO
		, AA.ICC
		, AA.CIUDAD
		, AA.PROVINCIA
		, AA.COD_CATEGORIA
		, AA.DOMAIN_LOGIN_OW
		, AA.NOMBRE_USUARIO_OW
		, AA.DOMAIN_LOGIN_SUB
		, AA.NOMBRE_USUARIO_SUB
		, AA.FORMA_PAGO
		, AA.COD_DA
		, AA.NOM_USUARIO
		, AA.CAMPANIA
		, AA.CODIGO_DISTRIBUIDOR
		, AA.CODIGO_PLAZA
		, AA.NOM_PLAZA
		, AA.REGION
		, AA.PROVINCIA_IVR
		, AA.EJECUTIVO_ASIGNADO_PTR
		, AA.AREA_PTR
		, AA.CODIGO_VENDEDOR_DA_PTR
		, AA.JEFATURA_PTR
		, AA.PROVINCIA_MS
		, AA.CODIGO_USUARIO
		, AA.CALF_RIESGO
		, AA.CAP_ENDEU
		, AA.VALOR_CRED
		, AA.VOL_INVOL
		, AA.ACCOUNT_NUM
		, AA.distribuidor_crm
		, AA.canal_transacc
		, AA.TARIFA_FINAL_PLAN_ACT
		, AA.descuento_tarifa_plan_act
		, AA.tarifa_plan_actual_ov
		, AA.descripcion_descuento_plan_act
		, ROW_NUMBER() OVER (
                PARTITION BY aa.TIPO
		, aa.TELEFONO
	ORDER BY
		aa.FECHA DESC
            ) AS RNUM
	FROM
		${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST AS AA
	WHERE
		FECHA < '${fecha_movimientos}'
		AND TIPO = 'ALTA'
    ) XX
WHERE
	XX.rnum = 1;
--OBTIENE EL ÛŒTIMO EVENTO DE LAS BAJAS EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.otc_t_baja_hist_unic;

CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_BAJA_HIST_UNIC AS
SELECT
	XX.TIPO
	, XX.TELEFONO
	, XX.FECHA
	, XX.CANAL
	, XX.SUB_CANAL
	, XX.NUEVO_SUB_CANAL
	, XX.PORTABILIDAD
	, XX.Operadora_origen
	, XX.Operadora_destino
	, XX.motivo
	, XX.DISTRIBUIDOR
	, XX.OFICINA
	--INSERTADO EN RF
	, XX.SUB_MOVIMIENTO
	, XX.IMEI
	, XX.EQUIPO
	, XX.ICC
	, XX.CIUDAD
	, XX.PROVINCIA
	, XX.COD_CATEGORIA
	, XX.DOMAIN_LOGIN_OW
	, XX.NOMBRE_USUARIO_OW
	, XX.DOMAIN_LOGIN_SUB
	, XX.NOMBRE_USUARIO_SUB
	, XX.FORMA_PAGO
	, XX.COD_DA
	, XX.NOM_USUARIO
	, XX.CAMPANIA
	, XX.CODIGO_DISTRIBUIDOR
	, XX.CODIGO_PLAZA
	, XX.NOM_PLAZA
	, XX.REGION
	, XX.PROVINCIA_IVR
	, XX.EJECUTIVO_ASIGNADO_PTR
	, XX.AREA_PTR
	, XX.CODIGO_VENDEDOR_DA_PTR
	, XX.JEFATURA_PTR
	, XX.PROVINCIA_MS
	, XX.CODIGO_USUARIO
	, XX.CALF_RIESGO
	, XX.CAP_ENDEU
	, XX.VALOR_CRED
	, XX.VOL_INVOL
	, XX.ACCOUNT_NUM
	, XX.distribuidor_crm
	, XX.canal_transacc
	, XX.TARIFA_FINAL_PLAN_ACT
	, XX.descuento_tarifa_plan_act
	, XX.tarifa_plan_actual_ov
	, XX.descripcion_descuento_plan_act
FROM
	(
	SELECT
		AA.TIPO
		, AA.TELEFONO
		, AA.FECHA
		, AA.CANAL
		, AA.SUB_CANAL
		, AA.NUEVO_SUB_CANAL
		, AA.PORTABILIDAD
		, AA.Operadora_origen
		, AA.Operadora_destino
		, AA.motivo
		, AA.DISTRIBUIDOR
		, AA.OFICINA
		--INSERTADO EN RF
		, AA.SUB_MOVIMIENTO
		, AA.IMEI
		, AA.EQUIPO
		, AA.ICC
		, AA.CIUDAD
		, AA.PROVINCIA
		, AA.COD_CATEGORIA
		, AA.DOMAIN_LOGIN_OW
		, AA.NOMBRE_USUARIO_OW
		, AA.DOMAIN_LOGIN_SUB
		, AA.NOMBRE_USUARIO_SUB
		, AA.FORMA_PAGO
		, AA.COD_DA
		, AA.NOM_USUARIO
		, AA.CAMPANIA
		, AA.CODIGO_DISTRIBUIDOR
		, AA.CODIGO_PLAZA
		, AA.NOM_PLAZA
		, AA.REGION
		, AA.PROVINCIA_IVR
		, AA.EJECUTIVO_ASIGNADO_PTR
		, AA.AREA_PTR
		, AA.CODIGO_VENDEDOR_DA_PTR
		, AA.JEFATURA_PTR
		, AA.PROVINCIA_MS
		, AA.CODIGO_USUARIO
		, AA.CALF_RIESGO
		, AA.CAP_ENDEU
		, AA.VALOR_CRED
		, AA.VOL_INVOL
		, AA.ACCOUNT_NUM
		, AA.distribuidor_crm
		, AA.canal_transacc
		, AA.TARIFA_FINAL_PLAN_ACT
		, AA.descuento_tarifa_plan_act
		, AA.tarifa_plan_actual_ov
		, AA.descripcion_descuento_plan_act
		---------------------------------------
		, ROW_NUMBER() OVER (
                PARTITION BY aa.TIPO
		,  
                aa.TELEFONO
	ORDER BY
		aa.FECHA DESC
            ) AS RNUM
	FROM
		${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST AS AA
	WHERE
		FECHA < '${fecha_movimientos}'
		AND TIPO = 'BAJA'
    ) XX
WHERE
	XX.rnum = 1;
--OBTIENE EL ÛŒTIMO EVENTO DE LAS TRANSFERENCIAS OUT EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.otc_t_pos_pre_hist_unic;

CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_POS_PRE_HIST_UNIC AS
SELECT
	XX.TIPO
	, XX.TELEFONO
	, XX.FECHA
	, XX.CANAL
	, XX.SUB_CANAL
	, XX.NUEVO_SUB_CANAL
	, XX.DISTRIBUIDOR
	, XX.OFICINA
	--    		iNSERTADO EN RF
	, XX.SUB_MOVIMIENTO
	, XX.IMEI
	, XX.EQUIPO
	, XX.ICC
	, XX.DOMAIN_LOGIN_OW
	, XX.NOMBRE_USUARIO_OW
	, XX.DOMAIN_LOGIN_SUB
	, XX.NOMBRE_USUARIO_SUB
	, XX.FORMA_PAGO
	, XX.canal_transacc
	, XX.CAMPANIA
	, XX.CODIGO_DISTRIBUIDOR
	, XX.CODIGO_PLAZA
	, XX.NOM_PLAZA
	, XX.REGION
	, XX.RUC_DISTRIBUIDOR -- ELIMINAR 
	, XX.EJECUTIVO_ASIGNADO_PTR
	, XX.AREA_PTR
	, XX.CODIGO_VENDEDOR_DA_PTR
	, XX.JEFATURA_PTR
	, XX.CODIGO_USUARIO
	, XX.CALF_RIESGO
	, XX.CAP_ENDEU
	, XX.VALOR_CRED
	, XX.ACCOUNT_NUM_ANTERIOR
	, XX.CIUDAD_USUARIO
	, XX.PROVINCIA_USUARIO
	, XX.ciudad
	, XX.COD_PLAN_ANTERIOR
	, XX.DES_PLAN_ANTERIOR
	, XX.distribuidor_crm
	, XX.TARIFA_FINAL_PLAN_ACT
	, XX.descuento_tarifa_plan_act
	, XX.tarifa_ov_plan_act
	--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
FROM
	(
	SELECT
		AA.TIPO
		, AA.TELEFONO
		, AA.FECHA
		, AA.CANAL
		, AA.SUB_CANAL
		, AA.NUEVO_SUB_CANAL
		, AA.DISTRIBUIDOR
		, AA.OFICINA
		--    		iNSERTADO EN RF
		, AA.SUB_MOVIMIENTO
		, AA.IMEI
		, AA.EQUIPO
		, AA.ICC
		, AA.DOMAIN_LOGIN_OW
		, AA.NOMBRE_USUARIO_OW
		, AA.DOMAIN_LOGIN_SUB
		, AA.NOMBRE_USUARIO_SUB
		, AA.FORMA_PAGO
		, AA.canal_transacc
		, AA.CAMPANIA
		, AA.CODIGO_DISTRIBUIDOR
		, AA.CODIGO_PLAZA
		, AA.NOM_PLAZA
		, AA.REGION
		, AA.RUC_DISTRIBUIDOR -- ELIMINAR 
		, AA.EJECUTIVO_ASIGNADO_PTR
		, AA.AREA_PTR
		, AA.CODIGO_VENDEDOR_DA_PTR
		, AA.JEFATURA_PTR
		, AA.CODIGO_USUARIO
		, AA.CALF_RIESGO
		, AA.CAP_ENDEU
		, AA.VALOR_CRED
		, AA.ACCOUNT_NUM_ANTERIOR
		, AA.CIUDAD_USUARIO
		, AA.PROVINCIA_USUARIO
		, AA.ciudad
		, AA.COD_PLAN_ANTERIOR
		, AA.DES_PLAN_ANTERIOR
		, AA.distribuidor_crm
		, AA.TARIFA_FINAL_PLAN_ACT
		, AA.descuento_tarifa_plan_act
		, AA.tarifa_ov_plan_act
		--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		, ROW_NUMBER() OVER (
                PARTITION BY aa.TIPO
		, aa.TELEFONO
	ORDER BY
		aa.FECHA DESC
            ) AS RNUM
	FROM
		${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST AS AA
	WHERE
		FECHA < '${fecha_movimientos}'
		AND TIPO = 'POS_PRE'
    ) XX
WHERE
	XX.rnum = 1;
--OBTIENE EL ÛŒTIMO EVENTO DE LAS TRANSFERENCIAS IN  EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.otc_t_pre_pos_hist_unic;

CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_PRE_POS_HIST_UNIC AS
SELECT
	XX.TIPO
	, XX.TELEFONO
	, XX.FECHA
	, XX.CANAL
	, XX.SUB_CANAL
	, XX.NUEVO_SUB_CANAL
	, XX.DISTRIBUIDOR
	, XX.OFICINA
	--    		iNSERTADO EN RF
	, XX.SUB_MOVIMIENTO
	, XX.IMEI
	, XX.EQUIPO
	, XX.ICC
	, XX.DOMAIN_LOGIN_OW
	, XX.NOMBRE_USUARIO_OW
	, XX.DOMAIN_LOGIN_SUB
	, XX.NOMBRE_USUARIO_SUB
	, XX.FORMA_PAGO
	, XX.canal_transacc
	, XX.CAMPANIA
	, XX.CODIGO_DISTRIBUIDOR
	, XX.CODIGO_PLAZA
	, XX.NOM_PLAZA
	, XX.REGION
	, XX.RUC_DISTRIBUIDOR -- ELIMINAR 
	, XX.EJECUTIVO_ASIGNADO_PTR
	, XX.AREA_PTR
	, XX.CODIGO_VENDEDOR_DA_PTR
	, XX.JEFATURA_PTR
	, XX.CODIGO_USUARIO
	, XX.CALF_RIESGO
	, XX.CAP_ENDEU
	, XX.VALOR_CRED
	, XX.ACCOUNT_NUM_ANTERIOR
	, XX.CIUDAD_USUARIO
	, XX.PROVINCIA_USUARIO
	, XX.ciudad
	, XX.COD_PLAN_ANTERIOR
	, XX.DES_PLAN_ANTERIOR
	, XX.distribuidor_crm
	, XX.TARIFA_FINAL_PLAN_ACT
	, XX.descuento_tarifa_plan_act
	, XX.tarifa_ov_plan_act
	--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
FROM
	(
	SELECT
		AA.TIPO
		, AA.TELEFONO
		, AA.FECHA
		, AA.CANAL
		, AA.SUB_CANAL
		, AA.NUEVO_SUB_CANAL
		, AA.DISTRIBUIDOR
		, AA.OFICINA
		--    		iNSERTADO EN RF
		, AA.SUB_MOVIMIENTO
		, AA.IMEI
		, AA.EQUIPO
		, AA.ICC
		, AA.DOMAIN_LOGIN_OW
		, AA.NOMBRE_USUARIO_OW
		, AA.DOMAIN_LOGIN_SUB
		, AA.NOMBRE_USUARIO_SUB
		, AA.FORMA_PAGO
		, AA.canal_transacc
		, AA.CAMPANIA
		, AA.CODIGO_DISTRIBUIDOR
		, AA.CODIGO_PLAZA
		, AA.NOM_PLAZA
		, AA.REGION
		, AA.RUC_DISTRIBUIDOR -- ELIMINAR 
		, AA.EJECUTIVO_ASIGNADO_PTR
		, AA.AREA_PTR
		, AA.CODIGO_VENDEDOR_DA_PTR
		, AA.JEFATURA_PTR
		, AA.CODIGO_USUARIO
		, AA.CALF_RIESGO
		, AA.CAP_ENDEU
		, AA.VALOR_CRED
		, AA.ACCOUNT_NUM_ANTERIOR
		, AA.CIUDAD_USUARIO
		, AA.PROVINCIA_USUARIO
		, AA.ciudad
		, AA.COD_PLAN_ANTERIOR
		, AA.DES_PLAN_ANTERIOR
		, AA.distribuidor_crm
		, AA.TARIFA_FINAL_PLAN_ACT
		, AA.descuento_tarifa_plan_act
		, AA.tarifa_ov_plan_act
		, ROW_NUMBER() OVER (
                PARTITION BY aa.TIPO
		, aa.TELEFONO
	ORDER BY
		aa.FECHA DESC
            ) AS RNUM
	FROM
		${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST AS AA
	WHERE
		FECHA < '${fecha_movimientos}'
		AND TIPO = 'PRE_POS'
    ) XX
WHERE
	XX.rnum = 1;
--OBTIENE EL ÛŒTIMO EVENTO DE LOS CAMBIOS DE PLAN EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.otc_t_cambio_plan_hist_unic;

CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST_UNIC AS
SELECT
	XX.TIPO
	, XX.TELEFONO
	, XX.FECHA
	, XX.CANAL
	, XX.SUB_CANAL
	, XX.NUEVO_SUB_CANAL
	, XX.DISTRIBUIDOR
	, XX.OFICINA
	, XX.COD_PLAN_ANTERIOR
	, XX.DES_PLAN_ANTERIOR
	, XX.TB_DESCUENTO
	, XX.TB_OVERRIDE
	, XX.DELTA
	--INSERTADO EN RF
	, XX.SUB_MOVIMIENTO
	, XX.DOMAIN_LOGIN_OW
	, XX.NOMBRE_USUARIO_OW
	, XX.DOMAIN_LOGIN_SUB
	, XX.NOMBRE_USUARIO_SUB
	, XX.FORMA_PAGO
	, XX.CAMPANIA
	, XX.CODIGO_DISTRIBUIDOR
	, XX.CODIGO_PLAZA
	, XX.NOM_PLAZA
	, XX.REGION
	, XX.RUC_DISTRIBUIDOR -- ELIMINAR
	, XX.TARIFA_BASICA_ANTERIOR
	, XX.FECHA_INICIO_PLAN_ANTERIOR
	, XX.TARIFA_FINAL_PLAN_ACT
	, XX.TARIFA_FINAL_PLAN_ANT
	, XX.PROVINCIA
	, XX.descripcion_descuento_plan_act
	, XX.descuento_tarifa_plan_act
	, XX.tarifa_plan_actual_ov
	-------------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-------------------------------------
FROM
	(
	SELECT
		AA.TIPO
		, AA.TELEFONO
		, AA.FECHA
		, AA.CANAL
		, AA.SUB_CANAL
		, AA.NUEVO_SUB_CANAL
		, AA.DISTRIBUIDOR
		, AA.OFICINA
		, AA.COD_PLAN_ANTERIOR
		, AA.DES_PLAN_ANTERIOR
		, AA.TB_DESCUENTO
		, AA.TB_OVERRIDE
		, AA.DELTA
		--INSERTADO EN RF
		, AA.SUB_MOVIMIENTO
		, AA.DOMAIN_LOGIN_OW
		, AA.NOMBRE_USUARIO_OW
		, AA.DOMAIN_LOGIN_SUB
		, AA.NOMBRE_USUARIO_SUB
		, AA.FORMA_PAGO
		, AA.CAMPANIA
		, AA.CODIGO_DISTRIBUIDOR
		, AA.CODIGO_PLAZA
		, AA.NOM_PLAZA
		, AA.REGION
		, AA.RUC_DISTRIBUIDOR  -- ELIMINAR
		, AA.TARIFA_BASICA_ANTERIOR
		, AA.FECHA_INICIO_PLAN_ANTERIOR
		, AA.TARIFA_FINAL_PLAN_ACT
		, AA.TARIFA_FINAL_PLAN_ANT
		, AA.PROVINCIA
		, AA.descripcion_descuento_plan_act
		, AA.descuento_tarifa_plan_act
		, AA.tarifa_plan_actual_ov
		-----------------------------------------
		, ROW_NUMBER() OVER (
                PARTITION BY aa.TELEFONO
	ORDER BY
		aa.FECHA DESC
            ) AS RNUM
	FROM
		${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST AS AA
	WHERE
		FECHA < '${fecha_movimientos}'
    ) XX
WHERE
	XX.rnum = 1;
--OBTIENE EL ÛŒTIMO EVENTO NO_RECICLABLE  EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.otc_t_no_reciclable_hist_unic;

CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_NO_RECICLABLE_HIST_UNIC AS
SELECT
	XX.TIPO
	, XX.SUB_MOVIMIENTO
	, XX.TELEFONO
	, XX.FECHA
	, XX.DOCUMENTO_CLIENTE_ACT
	, XX.FECHA_PROCESO
	, XX.CANAL_COMERCIAL
	, XX.CAMPANIA
	, XX.CODIGO_DISTRIBUIDOR
	, XX.NOM_DISTRIBUIDOR
	, XX.CODIGO_PLAZA
	, XX.NOM_PLAZA
	, XX.REGION
	, XX.RUC_DISTRIBUIDOR -- ELIMINAR
	, XX.LINEA_NEGOCIO_BAJA
	, XX.DOCUMENTO_CLIENTE_ANT
	, XX.DIAS
	, XX.FECHA_BAJA
FROM
	(
	SELECT
		AA.TIPO
		, AA.SUB_MOVIMIENTO
		, AA.TELEFONO
		, AA.FECHA
		, AA.DOCUMENTO_CLIENTE_ACT
		, AA.FECHA_PROCESO
		, AA.CANAL_COMERCIAL
		, AA.CAMPANIA
		, AA.CODIGO_DISTRIBUIDOR
		, AA.NOM_DISTRIBUIDOR
		, AA.CODIGO_PLAZA
		, AA.NOM_PLAZA
		, AA.REGION
		, AA.RUC_DISTRIBUIDOR -- ELIMINAR
		, AA.LINEA_NEGOCIO_BAJA
		, AA.DOCUMENTO_CLIENTE_ANT
		, AA.DIAS
		, AA.FECHA_BAJA
		------AAAAAAAAAAAAAAAAAAAAAAAAAAAAX------------------
		, ROW_NUMBER() 
          OVER (PARTITION BY aa.TIPO
		, aa.TELEFONO
	ORDER BY
		aa.FECHA DESC
            ) AS RNUM
	FROM
		${ESQUEMA_TABLA}.otc_t_no_reciclable_hist AS AA
	WHERE
		FECHA < '${fecha_movimientos}'
		---yyymmmdd
		AND TIPO = 'NO_RECICLABLE'
    ) XX
WHERE
	XX.rnum = 1;

---- primera DEPENDENCIA 
DROP TABLE ${ESQUEMA_TEMP}.otc_t_360_no_parque_trnsfr_tmp;

CREATE TABLE ${ESQUEMA_TEMP}.otc_t_360_no_parque_trnsfr_tmp AS
SELECT
	NUM_TELEFONICO AS TELEFONO
	, CAST(FECHA_ALTA AS date) AS FECHA_ALTA
	, FECHA_MOVIMIENTO_MES
	, datediff(FECHA_MOVIMIENTO_MES
	, FECHA_ALTA) AS dias_prepago
FROM
	--db_temporales.${TABLA_PIVOTANTE} 
	db_desarrollo2021.otc_t_360_parque_1_tmp
WHERE
	LINEA_NEGOCIO_HOMOLOGADO = 'PREPAGO'
	AND ES_PARQUE = 'NO'
	AND TIPO_MOVIMIENTO_MES = 'TRANSFER_OUT';
--REALIZAMOS EL CRUCE CON CADA TABLA USANDO LA TABLA PIVOT (TABLA RESULTANTE DE PIVOT_PARQUE) 
--Y AGREANDO LOS CAMPOS DE CADA TABLA RENOMBRANDOLOS DE ACUERDO AL MOVIMIENTO QUE CORRESPONDA.
--ESTA ES LA PRIMERA TABLA RESULTANTE QUE SERVIRA PARA ALIMENTAR LA ESTRUCTURA OTC_T_360_GENERAL.
DROP TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_tmp_t_mov;

CREATE TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_tmp_t_mov AS
SELECT
	Z.NUM_TELEFONICO
	, Z.CODIGO_PLAN
	, Z.FECHA_ALTA
	, Z.FECHA_LAST_STATUS
	, Z.ESTADO_ABONADO
	, Z.FECHA_PROCESO
	, Z.NUMERO_ABONADO
	, Z.LINEA_NEGOCIO
	-- LA LINEA DE ABAJO SE HA MODIFICADO para incluir account num de los movimientos BAJAS Y ALTAS BAJAS REPROCESO
	-- PARA LOS CUALES account num VIENE COMO null en la tabla pivotante
	, (CASE
		WHEN Z.ACCOUNT_NUM IS NULL THEN nvl(G.ACCOUNT_NUM, abr.ACCOUNT_NUM)
		ELSE Z.ACCOUNT_NUM	END) AS ACCOUNT_NUM
	, Z.SUB_SEGMENTO
	, Z.TIPO_DOC_CLIENTE
	, Z.IDENTIFICACION_CLIENTE
	, Z.CLIENTE
	, Z.CUSTOMER_REF
	, Z.COUNTED_DAYS
	, Z.LINEA_NEGOCIO_HOMOLOGADO
	, Z.CATEGORIA_PLAN
	, Z.TARIFA
	, Z.NOMBRE_PLAN
	, Z.MARCA
	, Z.CICLO_FACT
	, Z.CORREO_CLIENTE_PR
	, Z.TELEFONO_CLIENTE_PR
	, Z.IMEI
	, Z.ORDEN
	, Z.TIPO_MOVIMIENTO_MES
	, Z.FECHA_MOVIMIENTO_MES
	, Z.ES_PARQUE
	, Z.BANCO
	, A.FECHA AS FECHA_ALTA_HISTORICA
	, A.CANAL AS CANAL_ALTA
	, A.SUB_CANAL AS SUB_CANAL_ALTA
	, A.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_ALTA
	, A.DISTRIBUIDOR AS DISTRIBUIDOR_ALTA
	, A.OFICINA AS OFICINA_ALTA
	, nvl(A.PORTABILIDAD, abr.PORTABILIDAD) AS PORTABILIDAD
	, A.OPERADORA_ORIGEN
	, A.OPERADORA_DESTINO
	---nvl aniadido en REFACTORING, AL MOMENTO LA LINEA COMENTADA DE ABAJO 
	--- SOLO TRAE NULLS Y VACIOS, CON ESTE CAMBIO SE INCLUYEN LOS DE BAJAS 
	--,A.MOTIVO
	, NVL(G.MOTIVO, A.MOTIVO) AS MOTIVO
	, C.FECHA AS FECHA_PRE_POS
	, C.CANAL AS CANAL_PRE_POS
	, C.SUB_CANAL AS SUB_CANAL_PRE_POS
	, C.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_PRE_POS
	, C.DISTRIBUIDOR AS DISTRIBUIDOR_PRE_POS
	, C.OFICINA AS OFICINA_PRE_POS
	, D.FECHA AS FECHA_POS_PRE
	, D.CANAL AS CANAL_POS_PRE
	, D.SUB_CANAL AS SUB_CANAL_POS_PRE
	, D.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_POS_PRE
	, D.DISTRIBUIDOR AS DISTRIBUIDOR_POS_PRE
	, D.OFICINA AS OFICINA_POS_PRE
	, E.FECHA AS FECHA_CAMBIO_PLAN
	, E.CANAL AS CANAL_CAMBIO_PLAN
	, E.SUB_CANAL AS SUB_CANAL_CAMBIO_PLAN
	, E.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_CAMBIO_PLAN
	, E.DISTRIBUIDOR AS DISTRIBUIDOR_CAMBIO_PLAN
	, E.OFICINA AS OFICINA_CAMBIO_PLAN
	, nvl(nvl(E.COD_PLAN_ANTERIOR, D.COD_PLAN_ANTERIOR), C.COD_PLAN_ANTERIOR) AS COD_PLAN_ANTERIOR
	, nvl(nvl(E.DES_PLAN_ANTERIOR, D.DES_PLAN_ANTERIOR), C.DES_PLAN_ANTERIOR) AS DES_PLAN_ANTERIOR
	, E.TB_DESCUENTO
	, E.TB_OVERRIDE
	, E.DELTA
	-----------\/\/\/\/\/\/\/\/\/\/\/\/------------
	-----------INSERTADO EN REFACTORING------------
	, A.COD_CATEGORIA
	, A.COD_DA
	, A.NOM_USUARIO
	, A.PROVINCIA_IVR
	, A.PROVINCIA_MS
	, (CASE 
		WHEN UPPER(B.LINEA_NEGOCIO_BAJA) LIKE 'POSPAGO VPN' THEN 'POSPAGO'
		WHEN UPPER(B.LINEA_NEGOCIO_BAJA) LIKE '%H%BRIDO%' THEN 'POSPAGO'
		ELSE UPPER(B.LINEA_NEGOCIO_BAJA) END)	AS LINEA_DE_NEGOCIO_ANTERIOR
	, B.DOCUMENTO_CLIENTE_ANT AS CLIENTE_ANTERIOR
	, B.DIAS AS DIAS_RECICLAJE
	, B.FECHA_BAJA AS FECHA_BAJA_RECICLADA
	, D.ACCOUNT_NUM_ANTERIOR
	, E.TARIFA_BASICA_ANTERIOR
	, E.FECHA_INICIO_PLAN_ANTERIOR
	, nvl(nvl(E.TARIFA_FINAL_PLAN_ACT, A.TARIFA_FINAL_PLAN_ACT), C.TARIFA_FINAL_PLAN_ACT) AS TARIFA_FINAL_PLAN_ACT
	, nvl(nvl(E.descuento_tarifa_plan_act, A.descuento_tarifa_plan_act), C.descuento_tarifa_plan_act) AS descuento_tarifa_plan_act
	, nvl(nvl(E.tarifa_plan_actual_ov, A.tarifa_plan_actual_ov), C.tarifa_ov_plan_act) AS tarifa_plan_actual_ov
	, nvl(E.descripcion_descuento_plan_act, A.descripcion_descuento_plan_act) AS descripcion_descuento_plan_act
	, E.TARIFA_FINAL_PLAN_ANT
	--NVL ANIADIDO PARA INCLUIR LA FECHA DE BAJA DE LAS ALTAS_BAJAS_REPROCESO
	--, G.FECHA as  FECHA_MOVIMIENTO_BAJA
	, (CASE
		WHEN Z.TIPO_MOVIMIENTO_MES = 'BAJA' THEN G.FECHA
		ELSE D.FECHA END) AS FECHA_MOVIMIENTO_BAJA
	, G.VOL_INVOL
	, (CASE
		WHEN C.FECHA IS NOT NULL THEN
		(CASE 
			WHEN Z.ESTADO_ABONADO = TO_MES_ANT.ESTADO_ABONADO
			THEN 'SI'
			WHEN Z.ESTADO_ABONADO = A_MES_ANT.ESTADO_ABONADO   
			THEN 'SI'
			ELSE 'NO'		END)	END) AS MISMO_CLIENTE
	, (CASE
		WHEN Z.TIPO_MOVIMIENTO_MES LIKE 'TRANSFER_IN' THEN	NPT.dias_prepago
	END) AS DIAS_EN_PARQUE_PREPAGO
	, (CASE
		WHEN E.FECHA_INICIO_PLAN_ANTERIOR IS NULL
		AND E.FECHA > A.FECHA
		THEN datediff(E.FECHA, A.FECHA)
		ELSE datediff(E.FECHA, E.FECHA_INICIO_PLAN_ANTERIOR)
		END) AS DIAS_EN_PARQUE
	, (CASE
		WHEN Z.TIPO_MOVIMIENTO_MES = 'TRANSFER_IN' THEN 
		NPT.FECHA_ALTA	END) AS FECHA_ALTA_PREPAGO
	--------------FIN REFACTORING-----------------
	-----_______/\/\/\/\/\/\/\/\/\/\/\_____----
	--check! CAMBIO EN RF ${ESQUEMA_TEMP}POR db_temporales,   cambiar en produccion
FROM
	--db_temporales.${TABLA_PIVOTANTE} AS Z
	db_desarrollo2021.otc_t_360_parque_1_tmp AS Z
LEFT JOIN ${ESQUEMA_TABLA}.otc_t_alta_hist_unic AS A 
    ON
	(Z.NUM_TELEFONICO = A.TELEFONO)
LEFT JOIN ${ESQUEMA_TABLA}.otc_t_pre_pos_hist_unic AS C 
    ON
	(Z.NUM_TELEFONICO = C.TELEFONO)
	AND (Z.linea_negocio_homologado <> 'PREPAGO')
LEFT JOIN ${ESQUEMA_TABLA}.otc_t_pos_pre_hist_unic AS D 
    ON
	(Z.NUM_TELEFONICO = D.TELEFONO)
	AND (Z.linea_negocio_homologado = 'PREPAGO')
	-- LINEA_NEGOCIO_HOMOLOGADO SOLO ES PREPAGO  ,   POSPAGO O HOME
LEFT JOIN ${ESQUEMA_TABLA}.otc_t_cambio_plan_hist_unic AS E 
    ON
	(Z.NUM_TELEFONICO = E.TELEFONO)
	AND (Z.linea_negocio_homologado <> 'PREPAGO')
	---------&&&&&&&&&&&&&&&&---------------
	------INICIO REFACTORING 
LEFT JOIN ${ESQUEMA_CS_ALTAS}.otc_t_altas_bi AS A_MES_ANT 
    ON
	(Z.NUM_TELEFONICO = A_MES_ANT.TELEFONO)
	AND
	(Z.IDENTIFICACION_CLIENTE = A_MES_ANT.documento_cliente)
	AND
	(A_MES_ANT.P_FECHA_PROCESO = '${fecha_mes_ant_cp}')
	AND
	(A_MES_ANT.LINEA_NEGOCIO = 'PREPAGO')
LEFT JOIN ${ESQUEMA_CS_ALTAS}.otc_t_transfer_out_bi AS TO_MES_ANT 
    ON
	(Z.NUM_TELEFONICO = TO_MES_ANT.TELEFONO)
	AND
	(Z.IDENTIFICACION_CLIENTE = TO_MES_ANT.documento_cliente)
	AND
	(TO_MES_ANT.P_FECHA_PROCESO = '${fecha_mes_ant_cp}')
LEFT JOIN ${ESQUEMA_TABLA}.otc_t_baja_hist_unic AS G 
    ON
	(Z.NUM_TELEFONICO = G.TELEFONO)
LEFT JOIN ${ESQUEMA_TABLA}.otc_t_no_reciclable_hist_unic AS B 
    ON
	(NUM_TELEFONICO = B.TELEFONO)
LEFT JOIN ${ESQUEMA_TABLA}.otc_t_alta_baja_reproceso_hist AS abr 
    ON 
	(NUM_TELEFONICO = abr.TELEFONO)
LEFT JOIN ${ESQUEMA_TEMP}.otc_t_360_no_parque_trnsfr_tmp AS NPT
ON
	(Z.NUM_TELEFONICO = NPT.TELEFONO)
	------FIN REFACTORING
	-------&&&&&&&&&&&&&&&-----------------
    ;
--CREAMOS TABLA TEMPORAL UNION PARA OBTENER ULTIMO MOVIMIENTO DEL MES POR NUM_TELEFONO
DROP TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_mov_mes_tmp_2;

CREATE TABLE ${ESQUEMA_TEMP}.OTC_T_360_PARQUE_1_MOV_MES_TMP_2 AS
SELECT
	TIPO
	, TELEFONO
	, FECHA AS FECHA_MOVIMIENTO_MES
	, CANAL AS CANAL_MOVIMIENTO_MES
	, SUB_CANAL AS SUB_CANAL_MOVIMIENTO_MES
	, NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_MOVIMIENTO_MES
	, DISTRIBUIDOR AS DISTRIBUIDOR_MOVIMIENTO_MES
	, OFICINA AS OFICINA_MOVIMIENTO_MES
	, PORTABILIDAD AS PORTABILIDAD_MOVIMIENTO_MES
	, OPERADORA_ORIGEN AS OPERADORA_ORIGEN_MOVIMIENTO_MES
	, OPERADORA_DESTINO AS OPERADORA_DESTINO_MOVIMIENTO_MES
	, MOTIVO AS MOTIVO_MOVIMIENTO_MES
	, COD_PLAN_ANTERIOR AS COD_PLAN_ANTERIOR_MOVIMIENTO_MES
	, DES_PLAN_ANTERIOR AS DES_PLAN_ANTERIOR_MOVIMIENTO_MES
	, TB_DESCUENTO AS TB_DESCUENTO_MOVIMIENTO_MES
	, TB_OVERRIDE AS TB_OVERRIDE_MOVIMIENTO_MES
	, DELTA AS DELTA_MOVIMIENTO_MES
	--insertado en rf para unir campos y llevarlos a 360_general
	, SUB_MOVIMIENTO
	, IMEI
	, EQUIPO
	, ICC
	, DOMAIN_LOGIN_OW
	, NOMBRE_USUARIO_OW
	, DOMAIN_LOGIN_SUB
	, NOMBRE_USUARIO_SUB
	, FORMA_PAGO
	, EJECUTIVO_ASIGNADO_PTR
	, AREA_PTR
	, CODIGO_VENDEDOR_DA_PTR
	, JEFATURA_PTR
	, CODIGO_USUARIO
	, CALF_RIESGO
	, CAP_ENDEU
	, VALOR_CRED
	, CIUDAD_USUARIO
	, PROVINCIA_USUARIO
	, CIUDAD
	, provincia AS PROVINCIA_ACTIVACION
	, distribuidor_crm
	, canal_transacc
	, nom_plaza AS nom_plaza_MOVIMIENTO_MES
	, CODIGO_DISTRIBUIDOR AS CODIGO_DISTRIBUIDOR_MOVIMIENTO_MES
	, cod_da
	, CAMPANIA AS CAMPANIA_MOVIMIENTO_MES
	, REGION 
	-- FIN REFACTORING
FROM
	(
	SELECT
		TIPO
		, TELEFONO
		, FECHA
		, CANAL
		, SUB_CANAL
		, NUEVO_SUB_CANAL
		, DISTRIBUIDOR
		, OFICINA
		, PORTABILIDAD
		, OPERADORA_ORIGEN
		, OPERADORA_DESTINO
		, MOTIVO
		, COD_PLAN_ANTERIOR
		, DES_PLAN_ANTERIOR
		, TB_DESCUENTO
		, TB_OVERRIDE
		, DELTA
		--
        , SUB_MOVIMIENTO  
		, IMEI
		, EQUIPO
		, ICC
		, DOMAIN_LOGIN_OW
		, NOMBRE_USUARIO_OW
		, DOMAIN_LOGIN_SUB
		, NOMBRE_USUARIO_SUB
		, FORMA_PAGO
		, EJECUTIVO_ASIGNADO_PTR
		, AREA_PTR
		, CODIGO_VENDEDOR_DA_PTR
		, JEFATURA_PTR
		, CODIGO_USUARIO
		, CALF_RIESGO
		, CAP_ENDEU
		, VALOR_CRED
		, CIUDAD_USUARIO
		, PROVINCIA_USUARIO
		, CIUDAD
		, PROVINCIA
		, distribuidor_crm
		, canal_transacc
		, nom_plaza
		, CODIGO_DISTRIBUIDOR
		, cod_da
		, CAMPANIA
		, REGION
		, ROW_NUMBER() OVER (
                PARTITION BY TELEFONO
	ORDER BY
		FECHA DESC
            ) AS RNUM
	FROM
		(
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CAST(NULL AS STRING) AS CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, CAST(NULL AS STRING) AS PORTABILIDAD
			, CAST(NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST(NULL AS STRING) AS OPERADORA_DESTINO
			, CAST(NULL AS STRING) AS MOTIVO
			, COD_PLAN_ANTERIOR
			, DES_PLAN_ANTERIOR
			, TB_DESCUENTO
			, TB_OVERRIDE
			, DELTA
			--
            , SUB_MOVIMIENTO 
			, CAST(NULL AS STRING) AS IMEI
			, CAST(NULL AS STRING) AS EQUIPO
			, CAST(NULL AS STRING) AS ICC
			, DOMAIN_LOGIN_OW
			, NOMBRE_USUARIO_OW
			, DOMAIN_LOGIN_SUB
			, NOMBRE_USUARIO_SUB
			, FORMA_PAGO
			, CAST(NULL AS STRING) AS EJECUTIVO_ASIGNADO_PTR
			, CAST(NULL AS STRING) AS AREA_PTR
			, CAST(NULL AS STRING) AS CODIGO_VENDEDOR_DA_PTR
			, CAST(NULL AS STRING) AS JEFATURA_PTR
			, CAST(NULL AS STRING) AS CODIGO_USUARIO
			, CAST(NULL AS STRING) AS CALF_RIESGO
			, CAST(NULL AS STRING) AS CAP_ENDEU
			, CAST(NULL AS INT) AS VALOR_CRED
			, CAST(NULL AS STRING) AS CIUDAD_USUARIO
			, CAST(NULL AS STRING) AS PROVINCIA_USUARIO
			, CAST(NULL AS STRING) AS CIUDAD
			, PROVINCIA
			, CAST(NULL AS STRING) AS distribuidor_crm
			, CAST(NULL AS STRING) AS canal_transacc
			, nom_plaza
			, CODIGO_DISTRIBUIDOR
			, CAST(NULL AS STRING) AS cod_da
			, CAMPANIA
			, REGION
		FROM
			${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST_UNIC
		WHERE
			FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}'
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, CAST(NULL AS STRING) AS PORTABILIDAD
			, CAST(NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST(NULL AS STRING) AS OPERADORA_DESTINO
			, CAST(NULL AS STRING) AS MOTIVO
			, COD_PLAN_ANTERIOR
			, DES_PLAN_ANTERIOR
			, CAST(NULL AS DOUBLE) AS TB_DESCUENTO
			, CAST(NULL AS DOUBLE) AS TB_OVERRIDE
			, CAST(NULL AS DOUBLE) AS DELTA
			--
            , SUB_MOVIMIENTO  
			, IMEI
			, EQUIPO
			, ICC
			, DOMAIN_LOGIN_OW
			, NOMBRE_USUARIO_OW
			, DOMAIN_LOGIN_SUB
			, NOMBRE_USUARIO_SUB
			, FORMA_PAGO
			, EJECUTIVO_ASIGNADO_PTR
			, AREA_PTR
			, CODIGO_VENDEDOR_DA_PTR
			, JEFATURA_PTR
			, CODIGO_USUARIO
			, CALF_RIESGO
			, CAP_ENDEU
			, VALOR_CRED
			, CIUDAD_USUARIO
			, PROVINCIA_USUARIO
			, CIUDAD
			, CAST(NULL AS STRING) AS PROVINCIA
			, distribuidor_crm
			, canal_transacc
			, nom_plaza
			, CODIGO_DISTRIBUIDOR
			, CAST(NULL AS STRING) AS cod_da
			, CAMPANIA
			, REGION
		FROM
			${ESQUEMA_TABLA}.OTC_T_POS_PRE_HIST_UNIC
		WHERE
			FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}'
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, CAST(NULL AS STRING) AS PORTABILIDAD
			, CAST(NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST(NULL AS STRING) AS OPERADORA_DESTINO
			, CAST(NULL AS STRING) AS MOTIVO
			, COD_PLAN_ANTERIOR
			, DES_PLAN_ANTERIOR
			, CAST(NULL AS DOUBLE) AS TB_DESCUENTO
			, CAST(NULL AS DOUBLE) AS TB_OVERRIDE
			, CAST(NULL AS DOUBLE) AS DELTA
			--
            , SUB_MOVIMIENTO  
			, IMEI
			, EQUIPO
			, ICC
			, DOMAIN_LOGIN_OW
			, NOMBRE_USUARIO_OW
			, DOMAIN_LOGIN_SUB
			, NOMBRE_USUARIO_SUB
			, FORMA_PAGO
			, EJECUTIVO_ASIGNADO_PTR
			, AREA_PTR
			, CODIGO_VENDEDOR_DA_PTR
			, JEFATURA_PTR
			, CODIGO_USUARIO
			, CALF_RIESGO
			, CAP_ENDEU
			, VALOR_CRED
			, CIUDAD_USUARIO
			, PROVINCIA_USUARIO
			, CIUDAD
			, CAST(NULL AS STRING) AS PROVINCIA
			, distribuidor_crm
			, canal_transacc
			, nom_plaza
			, CODIGO_DISTRIBUIDOR
			, CAST(NULL AS STRING) AS cod_da
			, CAMPANIA
			, REGION
		FROM
			${ESQUEMA_TABLA}.OTC_T_PRE_POS_HIST_UNIC
		WHERE
			FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}'
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, PORTABILIDAD
			, OPERADORA_ORIGEN
			, OPERADORA_DESTINO
			, MOTIVO
			, CAST(NULL AS STRING) AS COD_PLAN_ANTERIOR
			, CAST(NULL AS STRING) AS DES_PLAN_ANTERIOR
			, CAST(NULL AS DOUBLE) AS TB_DESCUENTO
			, CAST(NULL AS DOUBLE) AS TB_OVERRIDE
			, CAST(NULL AS DOUBLE) AS DELTA
			, SUB_MOVIMIENTO
			, IMEI
			, EQUIPO
			, ICC
			, DOMAIN_LOGIN_OW
			, NOMBRE_USUARIO_OW
			, DOMAIN_LOGIN_SUB
			, NOMBRE_USUARIO_SUB
			, FORMA_PAGO
			, EJECUTIVO_ASIGNADO_PTR
			, AREA_PTR
			, CODIGO_VENDEDOR_DA_PTR
			, JEFATURA_PTR
			, CODIGO_USUARIO
			, CALF_RIESGO
			, CAP_ENDEU
			, VALOR_CRED
			, CAST(NULL AS STRING) AS CIUDAD_USUARIO
			, CAST(NULL AS STRING) AS PROVINCIA_USUARIO
			, CIUDAD
			, PROVINCIA
			, distribuidor_crm
			, canal_transacc
			, nom_plaza
			, CODIGO_DISTRIBUIDOR
			, cod_da
			, CAMPANIA
			, REGION
		FROM
			${ESQUEMA_TABLA}.OTC_T_BAJA_HIST_UNIC
		WHERE
			FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}'
			--- INSERTADO EN RF
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CAST(NULL AS STRING) AS CANAL
			, CAST(NULL AS STRING) AS SUB_CANAL
			, CAST(NULL AS STRING) AS NUEVO_SUB_CANAL
			, CAST(NULL AS STRING) AS DISTRIBUIDOR
			, CAST(NULL AS STRING) AS OFICINA
			, CAST(NULL AS STRING) AS PORTABILIDAD
			, CAST(NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST(NULL AS STRING) AS OPERADORA_DESTINO
			, CAST(NULL AS STRING) AS MOTIVO
			, CAST(NULL AS STRING) AS COD_PLAN_ANTERIOR
			, CAST(NULL AS STRING) AS DES_PLAN_ANTERIOR
			, CAST(NULL AS DOUBLE) AS TB_DESCUENTO
			, CAST(NULL AS DOUBLE) AS TB_OVERRIDE
			, CAST(NULL AS DOUBLE) AS DELTA
			--
            , SUB_MOVIMIENTO  
			, CAST(NULL AS STRING) AS IMEI
			, CAST(NULL AS STRING) AS EQUIPO
			, CAST(NULL AS STRING) AS ICC
			, CAST(NULL AS STRING) AS DOMAIN_LOGIN_OW
			, CAST(NULL AS STRING) AS NOMBRE_USUARIO_OW
			, CAST(NULL AS STRING) AS DOMAIN_LOGIN_SUB
			, CAST(NULL AS STRING) AS NOMBRE_USUARIO_SUB
			, CAST(NULL AS STRING) AS FORMA_PAGO
			, CAST(NULL AS STRING) AS EJECUTIVO_ASIGNADO_PTR
			, CAST(NULL AS STRING) AS AREA_PTR
			, CAST(NULL AS STRING) AS CODIGO_VENDEDOR_DA_PTR
			, CAST(NULL AS STRING) AS JEFATURA_PTR
			, CAST(NULL AS STRING) AS CODIGO_USUARIO
			, CAST(NULL AS STRING) AS CALF_RIESGO
			, CAST(NULL AS STRING) AS CAP_ENDEU
			, CAST(NULL AS INT) AS VALOR_CRED
			, CAST(NULL AS STRING) AS CIUDAD_USUARIO
			, CAST(NULL AS STRING) AS PROVINCIA_USUARIO
			, CAST(NULL AS STRING) AS CIUDAD
			, CAST(NULL AS STRING) AS PROVINCIA
			, CAST(NULL AS STRING) AS distribuidor_crm
			, CAST(NULL AS STRING) AS canal_transacc
			, nom_plaza
			, CODIGO_DISTRIBUIDOR
			, CAST(NULL AS STRING) AS cod_da
			, CAMPANIA
			, REGION
		FROM
			${ESQUEMA_TABLA}.OTC_T_NO_RECICLABLE_HIST_UNIC
		WHERE
			FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}'
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, fecha_baja AS FECHA
			, CANAL
			, SUB_CANAL
			, CAST(NULL AS STRING) AS NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, PORTABILIDAD
			, OPERADORA_ORIGEN
			, CAST(NULL AS STRING) AS OPERADORA_DESTINO
			, CAST(NULL AS STRING) AS MOTIVO
			, CAST(NULL AS STRING) AS COD_PLAN_ANTERIOR
			, CAST(NULL AS STRING) AS DES_PLAN_ANTERIOR
			, CAST(NULL AS DOUBLE) AS TB_DESCUENTO
			, CAST(NULL AS DOUBLE) AS TB_OVERRIDE
			, CAST(NULL AS DOUBLE) AS DELTA
			----------------------------------------------------------
			, SUB_MOVIMIENTO
			, IMEI
			, EQUIPO
			, ICC
			, DOMAIN_LOGIN_OW
			, NOMBRE_USUARIO_OW
			, DOMAIN_LOGIN_SUB
			, NOMBRE_USUARIO_SUB
			, FORMA_PAGO
			, EJECUTIVO_ASIGNADO_PTR
			, AREA_PTR
			, CODIGO_VENDEDOR_DA_PTR
			, JEFATURA_PTR
			, CODIGO_USUARIO
			, CALF_RIESGO
			, CAP_ENDEU
			, VALOR_CRED
			, CAST(NULL AS STRING) AS CIUDAD_USUARIO
			, CAST(NULL AS STRING) AS PROVINCIA_USUARIO
			, CAST(NULL AS STRING) AS CIUDAD
			, CAST(NULL AS STRING) AS PROVINCIA
			, distribuidor_crm
			, canal_transacc
			, nom_plaza
			, CODIGO_DISTRIBUIDOR
			, cod_da
			, CAMPANIA
			, REGION
		FROM
			${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_REPROCESO_HIST
		WHERE
			FECHA_alta BETWEEN '${f_inicio}' AND '${fecha_proceso}'
			-----------------------*************************-----------------
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, PORTABILIDAD
			, OPERADORA_ORIGEN
			, OPERADORA_DESTINO
			, MOTIVO
			, CAST(NULL AS STRING) AS COD_PLAN_ANTERIOR
			, CAST(NULL AS STRING) AS DES_PLAN_ANTERIOR
			, CAST(NULL AS DOUBLE) AS TB_DESCUENTO
			, CAST(NULL AS DOUBLE) AS TB_OVERRIDE
			, CAST(NULL AS DOUBLE) AS DELTA
			, SUB_MOVIMIENTO
			, IMEI
			, EQUIPO
			, ICC
			, DOMAIN_LOGIN_OW
			, NOMBRE_USUARIO_OW
			, DOMAIN_LOGIN_SUB
			, NOMBRE_USUARIO_SUB
			, FORMA_PAGO
			, EJECUTIVO_ASIGNADO_PTR
			, AREA_PTR
			, CODIGO_VENDEDOR_DA_PTR
			, JEFATURA_PTR
			, CODIGO_USUARIO
			, CALF_RIESGO
			, CAP_ENDEU
			, VALOR_CRED
			, CAST( NULL AS STRING) AS CIUDAD_USUARIO
			, CAST( NULL AS STRING) AS PROVINCIA_USUARIO
			, CIUDAD
			, PROVINCIA
			, distribuidor_crm
			, canal_transacc
			, nom_plaza
			, CODIGO_DISTRIBUIDOR
			, cod_da
			, CAMPANIA
			, REGION
		FROM
			${ESQUEMA_TABLA}.OTC_T_ALTA_HIST_UNIC
		WHERE
			FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}'
            ) ZZ
    ) TT
WHERE
	RNUM = 1;
--tabla temporal para el catalogo de USUARIOS pospago
DROP TABLE ${ESQUEMA_TEMP}.tmp_otc_t_ctl_pos_usr_nc;

CREATE TABLE ${ESQUEMA_TEMP}.TMP_OTC_T_CTL_POS_USR_NC AS 
SELECT
	*
FROM
	(
	SELECT
		usuario
		, nom_usuario
		, canal
		, campania
		, codigo_distribuidor
		, nom_distribuidor
		, regexp_replace(regexp_replace(codigo_plaza, '\n', ''), '¶', '') AS codigo_plaza
		, nom_plaza
		, ciudad
		, provincia
		, region
		, sub_canal
		, ruc_distribuidor
		, nuevo_subcanal
		, fecha
		, ROW_NUMBER() OVER(PARTITION BY usuario
	ORDER BY
		fecha DESC) AS rnum
	FROM
		${ESQUEMA_CS_ALTAS}.otc_t_ctl_pos_usr_nc
		--FROM db_reportes.otc_t_ctl_pos_usr_nc
		WHERE fecha <= '${fecha_proceso}'
) tt
WHERE
	rnum = 1;
--tabla temporal para el catalogo de USUARIOS prepago
DROP TABLE ${ESQUEMA_TEMP}.tmp_otc_t_ctl_pre_usr_nc;

CREATE TABLE ${ESQUEMA_TEMP}.TMP_OTC_T_CTL_Pre_USR_NC AS 
SELECT
	*
FROM
	(
	SELECT
		cod_generico
		, canal
		, codigo_distribuidor
		, nom_distribuidor
		, regexp_replace(regexp_replace(codigo_plaza, '\n', ''), '¶', '') AS codigo_plaza
		, nom_plaza
		, sub_canal
		, ruc_distribuidor
		, fecha
		, ROW_NUMBER() OVER(PARTITION BY cod_generico
	ORDER BY
		fecha DESC) AS rnum
	FROM
		db_desarrollo2021.otc_t_ctl_pre_usr_nc
	WHERE
		ruc_distribuidor <> 'nan') tt
WHERE
	rnum = 1;
----------TABLA UNION FINAL CON DATOS DEL CATALOGO DE USUARIOS
-- de aqui sale tipo de movimiento
DROP TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_mov_mes_tmp;

CREATE TABLE ${ESQUEMA_TEMP}.OTC_T_360_PARQUE_1_MOV_MES_TMP AS
SELECT
	A.*
	, CASE WHEN A.SUB_MOVIMIENTO IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO') 
	THEN NVL(PRE.CANAL,C.CANAL) ELSE C.CANAL END AS CANAL_COMERCIAL
	, CASE WHEN A.SUB_MOVIMIENTO IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO') 
	THEN NVL(A.CAMPANIA_MOVIMIENTO_MES,C.CAMPANIA) ELSE C.CAMPANIA END AS CAMPANIA_HOMOLOGADA
	, CASE WHEN A.SUB_MOVIMIENTO IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO') 
	THEN NVL(PRE.CODIGO_DISTRIBUIDOR,C.CODIGO_DISTRIBUIDOR) ELSE  C.CODIGO_DISTRIBUIDOR END AS CODIGO_DISTRIBUIDOR
	, CASE WHEN A.SUB_MOVIMIENTO IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO') 
	THEN NVL(PRE.NOM_DISTRIBUIDOR,C.NOM_DISTRIBUIDOR) ELSE C.NOM_DISTRIBUIDOR END AS NOM_DISTRIBUIDOR
	, CASE WHEN A.SUB_MOVIMIENTO IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO') 
	THEN NVL(PRE.CODIGO_PLAZA,C.CODIGO_PLAZA) ELSE C.CODIGO_PLAZA END AS CODIGO_PLAZA
	, CASE WHEN A.SUB_MOVIMIENTO IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO') 
	THEN NVL(PRE.NOM_PLAZA,C.NOM_PLAZA)  ELSE C.NOM_PLAZA END AS NOM_PLAZA
	, CASE WHEN A.SUB_MOVIMIENTO NOT IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO') 
	THEN NVL(C.REGION, A.REGION) ELSE A.REGION END  AS REGION_HOMOLOGADA
	, CASE WHEN A.SUB_MOVIMIENTO IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO') 
	THEN NVL(PRE.sub_canal,C.sub_canal) ELSE  C.sub_canal END AS sub_canal
	, CASE WHEN A.SUB_MOVIMIENTO IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO')
	THEN nvl(PRE.RUC_DISTRIBUIDOR, C.RUC_DISTRIBUIDOR) ELSE C.RUC_DISTRIBUIDOR END AS RUC_DISTRIBUIDOR
	, CASE WHEN A.SUB_MOVIMIENTO NOT IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO') 
	THEN C.nuevo_subcanal END AS nuevo_subcanal
	, CASE WHEN A.SUB_MOVIMIENTO NOT IN ('ALTA PREPAGO', 'ALTA PORTABILIDAD PREPAGO','TRANSFER OUT PREPAGO') 
	THEN C.nom_usuario END AS nom_usuario
FROM
	${ESQUEMA_TEMP}.OTC_T_360_PARQUE_1_MOV_MES_TMP_2 A
LEFT JOIN ${ESQUEMA_TEMP}.TMP_OTC_T_CTL_POS_USR_NC C
ON
	(A.DOMAIN_LOGIN_OW = C.USUARIO)
LEFT JOIN ${ESQUEMA_TEMP}.TMP_OTC_T_CTL_Pre_USR_NC pre
ON
	(A.cod_da = PRE.cod_generico)
;
--tercera tabla fuente:
DROP TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_mov_seg_tmp;

CREATE TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_mov_seg_tmp AS
SELECT
	TIPO AS ORIGEN_ALTA_SEGMENTO
	, TELEFONO
	, FECHA AS FECHA_ALTA_SEGMENTO
	, CANAL AS CANAL_ALTA_SEGMENTO
	, SUB_CANAL AS SUB_CANAL_ALTA_SEGMENTO
	, NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_ALTA_SEGMENTO
	, DISTRIBUIDOR AS DISTRIBUIDOR_ALTA_SEGMENTO
	, OFICINA AS OFICINA_ALTA_SEGMENTO
	, PORTABILIDAD AS PORTABILIDAD_ALTA_SEGMENTO
	, OPERADORA_ORIGEN AS OPERADORA_ORIGEN_ALTA_SEGMENTO
	, OPERADORA_DESTINO AS OPERADORA_DESTINO_ALTA_SEGMENTO
	, MOTIVO AS MOTIVO_ALTA_SEGMENTO
FROM
	(
	SELECT
		TIPO
		, TELEFONO
		, FECHA
		, CANAL
		, SUB_CANAL
		, NUEVO_SUB_CANAL
		, DISTRIBUIDOR
		, OFICINA
		, PORTABILIDAD
		, OPERADORA_ORIGEN
		, OPERADORA_DESTINO
		, MOTIVO
		,  
            ROW_NUMBER() OVER (
                PARTITION BY TELEFONO
	ORDER BY
		FECHA DESC
            ) AS RNUM
	FROM
		(
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, CAST(NULL AS STRING) AS PORTABILIDAD
			, CAST(NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST(NULL AS STRING) AS OPERADORA_DESTINO
			, CAST(NULL AS STRING) AS MOTIVO
		FROM
			${ESQUEMA_TABLA}.OTC_T_POS_PRE_HIST_UNIC
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, CAST(NULL AS STRING) AS PORTABILIDAD
			, CAST(NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST(NULL AS STRING) AS OPERADORA_DESTINO
			, CAST(NULL AS STRING) AS MOTIVO
		FROM
			${ESQUEMA_TABLA}.OTC_T_PRE_POS_HIST_UNIC
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, PORTABILIDAD
			, OPERADORA_ORIGEN
			, OPERADORA_DESTINO
			, MOTIVO
		FROM
			${ESQUEMA_TABLA}.OTC_T_ALTA_HIST_UNIC
            ) ZZ
    ) TT
WHERE
	RNUM = 1;
-- ESTA TABLA NO SE UTILIZA EN 360_GENERAL
DROP TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_tmp_t_mov_mes;

CREATE TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_tmp_t_mov_mes AS
SELECT
	NUM_TELEFONICO
	, CODIGO_PLAN
	, FECHA_ALTA
	, FECHA_LAST_STATUS
	, ESTADO_ABONADO
	, FECHA_PROCESO
	, NUMERO_ABONADO
	, LINEA_NEGOCIO
	, ACCOUNT_NUM
	, SUB_SEGMENTO
	, TIPO_DOC_CLIENTE
	, IDENTIFICACION_CLIENTE
	, CLIENTE
	, CUSTOMER_REF
	, COUNTED_DAYS
	, LINEA_NEGOCIO_HOMOLOGADO
	, CATEGORIA_PLAN
	, TARIFA
	, NOMBRE_PLAN
	, MARCA
	, CICLO_FACT
	, CORREO_CLIENTE_PR
	, TELEFONO_CLIENTE_PR
	, B.IMEI
	, ORDEN
	, TIPO_MOVIMIENTO_MES
	, B.FECHA_MOVIMIENTO_MES
	, ES_PARQUE
	, BANCO
	, CANAL_MOVIMIENTO_MES
	, SUB_CANAL_MOVIMIENTO_MES
	, NUEVO_SUB_CANAL_MOVIMIENTO_MES
	, DISTRIBUIDOR_MOVIMIENTO_MES
	, OFICINA_MOVIMIENTO_MES
	, PORTABILIDAD_MOVIMIENTO_MES
	, OPERADORA_ORIGEN_MOVIMIENTO_MES
	, OPERADORA_DESTINO_MOVIMIENTO_MES
	, MOTIVO_MOVIMIENTO_MES
	, COD_PLAN_ANTERIOR_MOVIMIENTO_MES
	, DES_PLAN_ANTERIOR_MOVIMIENTO_MES
	, TB_DESCUENTO_MOVIMIENTO_MES
	, TB_OVERRIDE_MOVIMIENTO_MES
	, DELTA_MOVIMIENTO_MES
FROM
	--check! CAMBIADO EN RF PARA ETAPA DE DESARROLLO ${ESQUEMA_TEMP} POR db_temporales
	--${ESQUEMA_TEMP}.${TABLA_PIVOTANTE} AS B
	--db_temporales.${TABLA_PIVOTANTE} AS B
	db_desarrollo2021.otc_t_360_parque_1_tmp AS B
LEFT JOIN ${ESQUEMA_TEMP}.OTC_T_360_PARQUE_1_MOV_MES_TMP AS A ON
	(NUM_TELEFONICO = A.TELEFONO)
	AND B.FECHA_MOVIMIENTO_MES = A.FECHA_MOVIMIENTO_MES;
----- PROCESO
--sh -x /home/nae108834/Cliente360_RF/bin/D_OTC_T_360_MOVIMIENTOS_PARQUE.sh 20220927
----- REPROCESO
--sh -x /home/nae108834/Cliente360_RF/bin/D_OTC_T_360_MOVIMIENTOS_PARQUE.sh 20220801 2
