DESC db_desarrollo2021.otc_t_360_general_rf;

CREATE TABLE db_desarrollo2021.otc_t_360_general_rf(
  num_telefonico string
, codigo_plan string
, usa_app string
, usuario_app string
, usa_movistar_play string
, usuario_movistar_play string
, fecha_alta timestamp
, nse double
, sexo string
, edad double
, mes string
, anio string
, segmento string
, linea_negocio string
, linea_negocio_homologado string
, forma_pago_factura varchar(40)
, forma_pago_alta string
, estado_abonado string
, sub_segmento string
, numero_abonado string
, account_num string
, identificacion_cliente string
, customer_ref string
, tac string
, tiene_bono string
, valor_bono double
, codigo_bono string
, probabilidad_churn double
, counted_days int
, categoria_plan string
, tarifa double
, nombre_plan string
, marca string
, grupo_prepago string
, fidelizacion_megas string
, fidelizacion_dumy string
, bancarizado string
, bono_combero string
, ticket_recarga string
, tiene_score_tiaxa string
, score_1_tiaxa double
, score_2_tiaxa double
, tipo_doc_cliente string
, nombre_cliente string
, ciclo_facturacion string
, email string
, telefono_contacto string
, fecha_ultima_renovacion date
, address_2 string
, address_3 string
, address_4 string
, fecha_fin_contrato_definitivo date
, vigencia_contrato int
, version_plan int
, fecha_ultima_renovacion_jn date
, fecha_ultimo_cambio_plan date
, tipo_movimiento_mes string
, fecha_movimiento_mes date
, es_parque string
, banco string
, parque_recargador string
, segmento_parque string
, susp_cobranza string
, susp_911 string
, susp_cobranza_puntual string
, susp_fraude string
, susp_robo string
, susp_voluntaria string
, vencimiento_cartera string
, saldo_cartera float
, fecha_alta_historia date
, canal_alta varchar(50)
, sub_canal_alta varchar(50)
, distribuidor_alta varchar(50)
, oficina_alta varchar(50)
---insertado en RF
, EQUIPO_ALTA string
, ICC_ALTA char(19)
, COD_CATEGORIA varchar(20)
, DOMAIN_LOGIN_OW_ALTA varchar(110)
, NOMBRE_USUARIO_OW_ALTA varchar(110)
, DOMAIN_LOGIN_SUB_ALTA varchar(110)
, NOMBRE_USUARIO_SUB_ALTA varchar(110)
, COD_DA string
, NOM_USUARIO string
, CAMPANIA_ALTA string
, CODIGO_DISTRIBUIDOR_ALTA varchar(60)
, CODIGO_PLAZA_ALTA varchar(60)
, NOM_PLAZA_ALTA varchar(110)
, REGION_ALTA string
, PROVINCIA_IVR string
, EJECUTIVO_ASIGNADO_PTR_ALTA string
, AREA_PTR_ALTA string
, CODIGO_VENDEDOR_DA_PTR_ALTA string
, JEFATURA_PTR_ALTA string
, PROVINCIA_MS string
, CODIGO_USUARIO_ALTA char(9)
, CALF_RIESGO_ALTA char(1)
, CAP_ENDEU_ALTA char(1)
, VALOR_CRED_ALTA int
----------------------
, portabilidad varchar(10)
, operadora_origen varchar(20)
, operadora_destino varchar(20)
, motivo varchar(50)
, fecha_pre_pos date
, canal_pre_pos varchar(50)
, sub_canal_pre_pos varchar(50)
----------INSERTADO EN RF
, FECHA_NR timestamp
, CANAL_COMERCIAL_NR string
, CAMPANIA_NR string
, CODIGO_DISTRIBUIDOR_NR string
, DISTRIBUIDOR_NR string
, CODIGO_PLAZA_NR string
, NOM_PLAZA_NR string
, REGION_NR string
, LINEA_NEGOCIO_BAJA string
, DOCUMENTO_CLIENTE_ANT string
, DIAS int
, FECHA_BAJA timestamp
---XXXXXXXXXXXXXXXXX----------------------------------------------------------------
----------------------------------------------------------------
, distribuidor_pre_pos varchar(50)
, oficina_pre_pos varchar(50)
, fecha_pos_pre date
, canal_pos_pre varchar(50)
, sub_canal_pos_pre varchar(50)
, EQUIPO_TI string
, ICC_TI char(19)
, DOMAIN_LOGIN_OW_TI varchar(110)
, NOMBRE_USUARIO_OW_TI varchar(110)
, DOMAIN_LOGIN_SUB_TI varchar(110)
, CODIGO_DISTRIBUIDOR_TI varchar(60)
, CODIGO_PLAZA_TI varchar(60)
, NOM_PLAZA_TI varchar(110)
, REGION_TI string
, EJECUTIVO_ASIGNADO_PTR_TI string
, AREA_PTR_TI string
, CODIGO_VENDEDOR_DA_PTR_TI string
, JEFATURA_PTR_TI string
, CODIGO_USUARIO_TI char(9)
, CALF_RIESGO_TI char(1)
, CAP_ENDEU_TI char(1)
, VALOR_CRED_TI int
, ACCOUNT_NUM_ANTERIOR_TI varchar(30)
, CIUDAD_USUARIO_TI varchar(40)
, PROVINCIA_USUARIO_TI varchar(40)
, MISMO_CLIENTE_TI char(2)
, EQUIPO_TO string
, ICC_TO char(19)
, DOMAIN_LOGIN_OW_TO varchar(110)
, NOMBRE_USUARIO_OW_TO varchar(110)
, DOMAIN_LOGIN_SUB_TO varchar(110)
, NOMBRE_USUARIO_SUB_TO varchar(110)
, CAMPANIA_TO string
, CODIGO_DISTRIBUIDOR_TO varchar(60)
, CODIGO_PLAZA_TO varchar(60)
, NOM_PLAZA_TO varchar(110)
, REGION_TO string
, EJECUTIVO_ASIGNADO_PTR_TO string
, AREA_PTR_TO string
, CODIGO_VENDEDOR_DA_PTR_TO string
, JEFATURA_PTR_TO string
, CODIGO_USUARIO_TO char(9)
, CALF_RIESGO_TO char(1)
, CAP_ENDEU_TO char(1)
, VALOR_CRED_TO int
, ACCOUNT_NUM_ANTERIOR_TO varchar(30)
, CIUDAD_USUARIO_TO varchar(40)
, PROVINCIA_USUARIO_TO varchar(40)
, MISMO_CLIENTE_TO char(2)
, distribuidor_pos_pre varchar(50)
, oficina_pos_pre varchar(50)
, fecha_cambio_plan date
, canal_cambio_plan varchar(50)
, sub_canal_cambio_plan varchar(50)
, DOMAIN_LOGIN_OW_CP varchar(110)
, NOMBRE_USUARIO_OW_CP varchar(110)
, DOMAIN_LOGIN_SUB_CP varchar(110)
, NOMBRE_USUARIO_SUB_CP varchar(110)
, CAMPANIA_CP string
, CODIGO_DISTRIBUIDOR_CP varchar(60)
, CODIGO_PLAZA_CP varchar(60)
, NOM_PLAZA_CP varchar(110)
, REGION_CP string
, NOMBRE_PLAN_ANTERIOR varchar(50)
, TARIFA_BASICA_ANTERIOR float
, FECHA_INICIO_PLAN_ANTERIOR date
, TARIFA_FINAL_PLAN_ACT float
, TARIFA_FINAL_PLAN_ANT float
-------------XXXXXXXXXXXXXXXXXXXXXXXXXXX-------------------------------------
----------------------------------------------------------------
, distribuidor_cambio_plan varchar(50)
, oficina_cambio_plan varchar(50)
, cod_plan_anterior varchar(10)
, des_plan_anterior varchar(50)
, tb_descuento double
, tb_override double
, delta double
, canal_movimiento_mes varchar(50)
, sub_canal_movimiento_mes varchar(50)
, distribuidor_movimiento_mes varchar(50)
, oficina_movimiento_mes varchar(50)
, portabilidad_movimiento_mes string
, operadora_origen_movimiento_mes string
, operadora_destino_movimiento_mes string
, motivo_movimiento_mes string
, cod_plan_anterior_movimiento_mes string
, des_plan_anterior_movimiento_mes string
, tb_descuento_movimiento_mes double
, tb_override_movimiento_mes double
, delta_movimiento_mes double
, fecha_alta_cuenta date
, fecha_inicio_pago_actual date
, fecha_fin_pago_actual date
, fecha_inicio_pago_anterior date
, fecha_fin_pago_anterior date
, forma_pago_anterior varchar(40)
, origen_alta_segmento varchar(20)
, fecha_alta_segmento date
, dias_voz int
, dias_datos int
, dias_sms int
, dias_contenido int
, dias_total int
, limite_credito double
, adendum double
, fecha_registro_app date
, perfil string
, usuario_web string
, fecha_registro_web timestamp
, fecha_nacimiento date COMMENT 'Fecha de nacimiento del cliente en formato YYYY-MM-DD')
PARTITIONED BY ( 
  fecha_proceso bigint)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
LOCATION
  'hdfs://quisrvbigdataha/apps/hive/warehouse/db_desarrollo2021.db/otc_t_360_general'
TBLPROPERTIES (
  'orc.compress' = 'SNAPPY'
, 
  'transient_lastDdlTime' = '1644361593')
